### ISSUE TITLE
Explanation about the "what" post

### ISSUE THREAD

**Issue by ShadowJonathan** [KaityyUwU/FediCW#2]
I've used this one fairly often, to the degree that i feel like ive started a trend.

In my eyes, the "what" tag is *everything* that someone might say "what" to, its meant to be comprehensible, but so far out of wack that, while you can understand it, its like "wh- what, why, huh" when you'd read it

"???" is more or less meant to be "you're not completely supposed to understand it, this is a random cohesive blurb" of sorts

Just a bit of side-chatter to the meanings, feel free to close :3

**Comment by KaityyUwU** [comment]
Yeah I think it would probably be good to re-phrase those too. I'm a little busy at the moment but I'll close once I've had the chance to edit the definitions
